# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Classes = [
    {
        'cid': '{6b55121f-8148-46e1-a8e4-66e0f4e17e5c}',
        'contract_ids': ['@mozilla.org/network/protocol;1?name=aeon'],
        'esModule': 'resource:///modules/AeonProtocolHandler.sys.mjs',
        'constructor': 'AeonProtocolHandler',
        'protocol_config': {
            'scheme': 'aeon',
            'flags': [
                'URI_STD',
                'URI_DANGEROUS_TO_LOAD',
            ],
        },
    },
]
